pipeline:
  name: LibraryManagement
  identifier: LibraryManagement
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: ci-stage
        identifier: cistage
        description: ""
        type: CI
        spec:
          cloneCodebase: false
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    connectorRef: account.harnessImage
                    image: eclipse-temurin:17-jdk-alpine
                    shell: Sh
                    command: |-
                      java --version
                      mvn clean install -DskipTests 
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPushDockerRegistry_1
                  identifier: BuildAndPushDockerRegistry_1
                  spec:
                    connectorRef: docker_connector
                    repo: sarthaksatish/librarymanagementsystem
                    tags:
                      - latest
          caching:
            enabled: true
            paths: []
