apiVersion: v1
kind: Pod
metadata:
  labels:
    jenkins: jenkins-pipeline
spec:
  volumes:
    - name: sharedvolume
      emptyDir: {}
    - name: kaniko-secret
      secret:
        secretName: dockercred
        items:
          - key: .dockerconfigjson
            path: config.json
  serviceAccountName: jenkins
  securityContext:
    runAsUser: 0
  containers:
    - name: helm
      image: "justinrlee/helm3"
      ttyEnabled: true
      command:
        - sleep
      args:
        - "9999999"
      # resources:
      #   requests:
      #     memory: "128Mi"
      #     cpu: "1"
      #   limits:
      #     memory: "500Mi"
      #     cpu: "2"
    - name: kaniko
      image: gcr.io/kaniko-project/executor:debug
      command:
        - sleep
      args:
        - "9999999"
      volumeMounts:
        - name: kaniko-secret
          mountPath: /kaniko/.docker
      # resources:
      #   requests:
      #     memory: "128Mi"
      #     cpu: "1"
      #   limits:
      #     memory: "500Mi"
      #     cpu: "2"
    - name: maven
      image: maven:3.9.4-amazoncorretto-17
      imagePullPolicy: Always
      ttyEnabled: true
      command:
        - sleep
      args:
        - 99d
      # resources:
      #   requests:
      #     memory: "128Mi"
      #     cpu: "1"
      #   limits:
      #     memory: "500Mi"
      #     cpu: "2"
    - name: python
      image: python:latest
      imagePullPolicy: Always
      command:
        - sleep
        - "1000"
      tty: true
      # resources:
      #   requests:
      #     memory: "128Mi"
      #     cpu: "1"
      #   limits:
      #     memory: "500Mi"
      #     cpu: "2"