apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: librarymanagementsys
  name: librarymanagementsvc
spec:
  ports:
  - port: 8085
    protocol: TCP
    targetPort: 8085
  selector:
    app: librarymanagementsys
status:
  loadBalancer: {}
